# Static build version - changing the version dynamically means you can't
# just click from github to see how things are progressing until the build has
# finished, which could be a bit annoying.
version: 1.{build}-{branch}

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# build only master branch
branches:
  only:
    - master

# Skip building commits if only the following directories/files are changed
skip_commits:
  files:
    - .gitignore
    - .travis.yml
    - .clang-format
    - '**/*.md'
    - debian-packager/
    - bin/PCSX2_keys.ini.default
    # Linux only plugins for now
    - plugins/onepad/
    - plugins/onepad_legacy/

environment:
  matrix:
  - platform: Win32
    target: AppVeyor
    visualstudio_string: vs2019
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  - platform: x64
    target: AppVeyor
    visualstudio_string: vs2019
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

matrix:
  fast_finish: true

init:
# Use CRLF line endings on Windows so users can just use Notepad.
  - git config --global core.autocrlf true

install:
  - git submodule update --init --recursive

build_script:
  - msbuild buildbot.xml /m /t:%target% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - ps: $env:gitrev = git describe --tags
  - ps: $env:my_version = "$env:gitrev-$env:appveyor_build_number"
  - type NUL > bin\portable.ini
  - set folder_name=pcsx2-%my_version%-%visualstudio_string%-%platform%-%target%
  - rename bin %folder_name%
  - 7z a -mx9 %folder_name%.7z %folder_name%

test: off

artifacts:
  - path: $(folder_name).7z
    name: $(visualstudio_string)-$(target)
