name: Remove Old Artifacts

# NOTE - Cleaning artifacts is necessary, storage is limited and the default, not configurable time window is 90 days
# this is likely too long, so this action will periodically cleanup old artifacts
# - https://github.com/marketplace/actions/remove-artifacts
# There is a _lot_ of confusion around the limit for artifacts though - https://github.com/godotengine/godot-proposals/issues/1412#issuecomment-680173450
# - So likely something we want to bake for a while and see how it goes.

on:
  schedule:
    # Every day at 1am
    - cron: "0 1 * * *"

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: "1 month"
          skip-tags: true
