name: 🐧 Linux Builds

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build_linux_qt_sse4:
    name: "AppImage"
    uses: ./.github/workflows/linux_build_qt.yml
    with:
      jobName: "Qt SSE4"
      compiler: clang
      cmakeflags: ""
      simd: "SSE4"
      buildAppImage: true
    secrets: inherit

  build_linux_qt_avx2:
    name: "AppImage"
    uses: ./.github/workflows/linux_build_qt.yml
    with:
      jobName: "Qt AVX2"
      detail: ""
      compiler: clang
      cmakeflags: "-DARCH_FLAG=-march=haswell"
      simd: "AVX2"
      buildAppImage: true
    secrets: inherit
